basic_settings:
  site_title: Griffin Chure, PhD
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'About'
      url: '/about/'
    - title: 'CV'
      url: '/cv/'
    - title: 'Research'
      url: '/research/'
    - title: 'Teaching'
      url: '/teaching/'
    - title: 'Showcase'
      url: '/showcase/' 
    - title: 'Photography'
      url: 'https://gchure.github.io/photography'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: '<a href="http://mailto:gchure@stanford.edu"> gchure@stanford.edu</a>'

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 5

social_settings:
  twitter_url: 'http://twitter.com/gdchure'
  orcid_url: 'https://orcid.org/0000-0002-2216-2057' 
  github_url: 'http://github.com/gchure'


color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#4b4b4b'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#4f76ba' #'#5F2E88' #F2784B'
  border_color: '#dddddd'
  overlay_background_color: '#3c3c3c'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#3c3c3c'
  error_color: '#D64541'

font_settings:
  font_embed: ' <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&family=Nunito+Sans:ital,wght@0,300;0,400;0,600;1,300;1,400;1,600&display=swap" rel="stylesheet">'
  title_font: '"Crimson Text", sans-serif'
  body_font: '"Nunito Sans", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 20 
    medium_size: 25 
    large_size: 30 
    weight: 300
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 300
    letter_spacing: 1
  grid_item_title:
    small_size: 12
    medium_size: 20
    large_size: 35
    weight: 150
    letter_spacing: 0
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 300
    letter_spacing: 0
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 12
    medium_size: 15
    large_size: 16
    weight: 300
    letter_spacing: 0
    line_height: 1.4
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: >
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-109526846-1', 'auto');
    ga('send', 'pageview');
    </script>
  custom_styles: ""
  header_js: ""
  footer_js: ""